### ISSUE TITLE
전략 패턴 설명 오류

### ISSUE THREAD

**Issue by simp7** [ksundong/backend-interview-question#16]
디자인 패턴 - 전략 패턴의 설명이 전략 패턴 보다는 가교 패턴에 가까운 것 같습니다.
두 패턴 모두 작동 원리는 비슷합니다. 다만 전략 패턴은 행동 패턴으로 '알고리즘의 캡슐화'를 주요한 목적으로 하고 있는 반면 가교 패턴은 구조 패턴으로 '추상과 구현을 분리'를 주요한 목적으로 하고 있습니다.(에릭 감마 외 3인, GoF의 디자인 패턴, 프로텍 미디어, 2015)
오류인지 아닌지 확실하지 않아서 이슈로 남깁니다. 만약 이슈가 채택되면 해당 부분을 수정해 보겠습니다.

**Comment by ksundong** [comment]
좋은 지적이라고 생각됩니다.
저도 한 번 학습해봐야겠네요.

**Comment by simp7** [comment]
좀더 자세히 공부하고 보니 틀린 설명은 아닌 것 같습니다. 다만 #17에서 가교 패턴을 추가하면서 차별화를 위해 전략 패턴의 내용을 수정했습니다. 해당 수정 사항이 괜찮은지 봐주시면 감사하겠습니다.
