### ISSUE TITLE
N + 1 문제 발생 이유 설명 보완

### ISSUE THREAD

**Issue by zwan2** [ksundong/backend-interview-question#26]
> N + 1 쿼리는 JPA의 프록시로 인한 지연 로딩 때문에 발생합니다. 

의도를 제가 잘 파악한 것인지 모르겠지만, 일반적으로 N + 1 문제는 즉시로딩을 사용할 때 많이 발생합니다.
또한, 지연 로딩을 사용하더라도 말씀하신 것처럼 프록시가 엔티티를 가져오는 단계에서는 N + 1 문제가 발생합니다.

N + 1 쿼리의 발생 이유는 `JPQL이 영속성 컨텍스트를 고려하지 않고 항상 데이터베이스에서 직접 결과를 조회하려고 하는 특성 때문`이라고 설명하는 게 적절하다고 생각합니다.

**Comment by ksundong** [comment]
안녕하세요. 좋은 의견 감사합니다.
N + 1 문제는 즉시로딩이나 지연로딩 둘다 사용할 때 유의하지 않으면 발생할 수 있다고 생각합니다. (둘 중 뭐가 더 일반적이다 말할 수 없는 성질이라고 보여집니다.)
제가 당시에 EAGER 로딩 전략을 사용하지 않았던 탓에 말씀하신 내용이 답변에 누락되어 있었네요.

말씀하신 내용은 즉시로딩 시점에만 해당한다고 생각됩니다.
제가 이 글을 늦은시간에 봐서 직접 JPA를 사용하지는 않고 사고실험을 해보자면, 지연로딩 전략을 사용한 하위 엔티티의 경우에는 해당 엔티티가 영속성 컨텍스트에 이미 존재하면 N + 1 쿼리가 발생하지 않을 것이라고 생각됩니다. (이 사고실험이 틀렸다면 아래의 제 내용도 틀린 것입니다.)

좀 더 생각을 정리해보자면, 즉시 로딩의 경우는 말씀하신 내용이 맞고, 지연 로딩은 Proxy 객체를 unproxy 하는 시점에 영속성 컨텍스트에 엔티티가 존재하지 않는 경우 추가 쿼리가 발생하는 부분이기 때문에 말씀하신 내용과는 약간 다른 측면을 띄고 있다고 보여집니다. 따라서 각각에 대한 원인이 존재한다는 생각이 드네요.

**Comment by ksundong** [comment]
해당 Issue Close 하겠습니다.
추가 의견이 있으신 경우 Open 해주세요!
