### ISSUE TITLE
CS 관련 지식 - 언어 관련 - Java - JVM의 구조와 Java의 실행방식 설명해주세요. - 영문 오타 수정

### ISSUE THREAD

**Issue by seheonCho** [ksundong/backend-interview-question#29]
안녕하세요. 오타를 수정하려고 합니다.

CS 관련 지식 - 언어 관련 - Java - JVM의 구조와 Java의 실행방식 설명해주세요. - 영문 오타 수정

Exection engine -> Execution engine

해당 레포에서 지식을 잘 습득하고 있습니다, 레포에 도움이 되었으면 합니다.

감사합니다.

**Comment by ksundong** [comment]
@seheonCho 
안녕하세요! 기여에 감사드립니다. 🙇‍♂️
혹시 해당 내용으로 PR을 올려주셔도 좋을 것 같은데, 가능하실까요~?
다음주까지 PR이 올라오지 않으면 제가 수정처리 하겠습니다~ 감사합니다~
