### ISSUE TITLE
과제 전형 질문드립니다.

### ISSUE THREAD

**Issue by Rebwon** [ksundong/backend-interview-question#5]
깃허브나 구글에 떠돌아다니는 실제 과제 전형을 구현해보는 그런 내용은 해당 레포지토리와 무관한가요?

**Comment by ksundong** [comment]
@Rebwon 
일단 제 의도는 기술면접에 한해서 정리하려는 의도였습니다.
과제 구현의 경우는 보통 설계능력을 본다고 생각했기 때문에 이런 부분은 애플리케이션을 개발하는 과정에서 습득할 수 있지 않을까 싶어요.
프로젝트의 아이디어를 제공하는 것이나, 좋은 설계를 위한 개선 포인트를 정리하는건 연관이 있을 것 같아요.

**Comment by Rebwon** [comment]
과제 전형은 아무래도 개인마다 설계와 구현에 차등이 있기에, 추상적으로 아이디어 제공을 하거나 하는 쪽으로 생각해보겠습니다. 요즘 과제 전형이 점점 늘어나는 추세라 여쭤보았습니다. 답변 감사합니다.

**Comment by ksundong** [comment]
@Rebwon 
넵 좋은 의견 감사합니다~
